---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data-pvc
  namespace: infra
  annotations:
    # volume.beta.kubernetes.io/storage-class: "ibmc-block-bronze"
    # volume.beta.kubernetes.io/storage-class: twddstg
    volume.beta.kubernetes.io/storage-class: managed-nfs-storage-retain
  # labels:
  #   billingType: "hourly"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
