---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: infra
  labels:
    app: phpmyadmin
    release: mariadb-infra
    tier: frontend
spec:
  ports:
  - name: phpmyadmin
    port: 80
    protocol: TCP
    nodePort: 30002
  selector:
    app: phpmyadmin
    tier: frontend
  type: NodePort
